# Generated by Django 4.1 on 2022-11-27 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_location_skills'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
    ]
