# Generated by Django 4.1 on 2022-11-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='demo_link_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
